os: Visual Studio 2015
install:
  - cmd: mkdir opencvbuild
  - cmd: cd opencvbuild
  - cmd: mkdir build
  - cmd: mkdir source
  - cmd: choco install opencv
  - cmd: cd ..
  - set QTDIR=C:C:\Qt\5.6\msvc2015_64
  
build_script:
  - Nmake