version: '{branch}-{build}'

os: Visual Studio 2015

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  OpenCV_DIR: C:\tools\opencv\build
  QTDIR: C:\Qt\5.6\msvc2015_64
  
  #VSVER: 14.0 # Visual Studio 2015
  #matrix:
    #- QTDIR: C:\Qt\5.3\mingw482_32
    #- QTDIR: C:\Qt\5.4\mingw491_32
    #- QTDIR: C:\Qt\5.6\mingw49_32
    #- QTDIR: C:\Qt\5.6\msvc2015
    #- QTDIR: C:\Qt\5.6\msvc2015_64

configuration:
  #- debug
  - release

install:
  #- '%QTDIR%\bin\qtenv2.bat'
  - cmd: choco install opencv
  #- cmd: choco install cmake
  #- qmake -v
  #- if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  #- if %QTDIR:msvc=%==%QTDIR% g++ --version
  #- if %QTDIR:msvc=%==%QTDIR% set make=mingw32-make.exe
  #- if %QTDIR:msvc=%==%QTDIR% %make% --version
  #- if not %QTDIR:msvc=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio %VSVER%\VC\vcvarsall.bat" %ARCH%
  #- if not %QTDIR:msvc=%==%QTDIR% set make=nmake.exe
  #- if not %QTDIR:msvc=%==%QTDIR% %make% /? > nul

  #- set QTDIR
before_build:
  #- mkdir %APPVEYOR_BUILD_FOLDER%-build
  #- cd %APPVEYOR_BUILD_FOLDER%-build
  #- cd %APPVEYOR_BUILD_FOLDER% 
  #- qmake -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%
#  - cmd: set OpenCV_DIR=C:\tools\opencv\build\x64\vc12\lib
#  - cmd: set PATH=C:\tools\opencv\build\bin:%PATH%

  - mkdir build
  - cmake build c:\projects\hello-qt
#build_script:
#  - cmake --build build

artifacts:
  - path: $(configuration)\Giteye.exe
    name: Giteye

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
