version: '{build}'
skip_tags: false
os: MinGW
shallow_clone: true
environment:
  matrix:
  - CMAKE_GENERATOR: MinGW Makefiles
    QTDIR: C:\Qt\5.6\mingw49_32
    MINGW: C:\Qt\Tools\mingw492_32
 configuration:
- RelWithDebInfo
matrix:
  fast_finish: true
build_script:
- cmd: '%SCRIPT%'
artifacts:
- path: INSTALL
  name: neovim-qt
