version: '{build}'
skip_tags: false
os: MinGW
shallow_clone: true
environment:
  matrix:
  - CMAKE_GENERATOR: MinGW Makefiles
    QTDIR: C:\Qt\5.6\mingw49_32
    MINGW: C:\Qt\Tools\mingw492_32
configuration:
- RelWithDebInfo
matrix:
  fast_finish: true
build_script:
- cmd: '%SCRIPT%'
deploy:
  provider: GitHub
  auth_token:
    secure: 9bMCGL2D0e/GK3MGOJu7Ma1hNb6sxAOyEftuonF/tV31LoLLM77+hitI6T3snyCM
 
